import bcrypt from 'bcryptjs';

const data = {
  users: [
    {
      name: 'Krishna',
      email: 'AdminKrishna@untitledarts.com',
      password: bcrypt.hashSync('Krishna@123', 8),
      isAdmin: true,
      isSeller: true,
      mobile:'9182790633',
      seller: {
        name: 'UA',
        logo: '/images/DP1.jpg',
        description: 'best seller',
        rating: 4.5,
        numReviews: 120,
      },
    },
    {
      name: 'Srinivas',
      email: 'AdminSrinivas@untitledarts.com',
      password: bcrypt.hashSync('Srinivas@123', 8),
      isAdmin: true,
      isSeller: true,
      mobile:'9182790633',
      seller: {
        name: 'UA2',
        logo: '/images/K2.jpg',
        description: 'best seller',
        rating: 4.5,
        numReviews: 120,
      },
    },
    {
      name: 'praveen',
      email: 'Userpraveen@untitledarts.com',
      password: bcrypt.hashSync('1234', 8),
      isAdmin: false,
    },
  ],
  products: [
    {
      "id": 1,
      "name": "Rice pot",
      "category": "Utensils",
      "image": "/images/RP2.jpg",
      "brand": "Terracotta",
      "rating": 4.7,
      "numReviews": 10,
      "Large": 1,
      "Medium": 1,
      "Small": 1,
      "countInStock":50,
      "Ldimension": "25x25x20(cm)-3.75lts",
      "Mdimension": "22x22x14(cm)-3 lts",
      "Sdimension": "20x20x14(cm)-2 lts",
      "color": "Brown",
      "painted": 0,
      "price":350,
      "Lprice": 450,
      "Mprice": 350,
      "Sprice": 250,
      "Lstock": 50,
      "Mstock": 50,
      "Sstock": 50,
      "lid": 1,
      "material": "terracotta",
      "howToUse":"Dip the utensil completely in water for a day & then fill the vessel with rice starch for few hours.When the vessel is hot do not pour cold water, let the vessel temperature come to normal then wash.",
      "WashingTips":"Always avoid Metallic scrubber rather use Soft sponge. Simply use hot water with lime. Avoid cleaning earthenware with a soap or detergent or in a dish washer.",
      "Storage":"Allow the vessel to dry completely before storage. Once in a week Fill half the vessel with water, boil for 3 min & then dispose the water to remove oil & stains, this will also strengthen & hygiene the utensil.",
      "description": "Ethnic ricepot to relish the taste and health what our elders had"
    },
    {
      "id": 2,
      "name": "Curry pot",
      "category": "Utensils",
      "image": "/images/CM1.jpg",
      "brand": "Terracotta",
      "rating": 4.3,
      "numReviews": 15,
      "Large": 1,
      "Medium": 1,
      "Small": 1,
      "countInStock":50,
      "Ldimension": "25x25x20(cm)-3.75 lts",
      "Mdimension": "23x23x14(cm)-3 lts",
      "Sdimension": "20x20x14(cm)-2 lts",
      "color": "Brown",
      "painted": 0,
      "Lprice": 400,
      "Mprice": 300,
      "Sprice": 250,
      "price":350,
      "Lstock": 50,
      "Mstock": 50,
      "Sstock": 50,
      "lid": 1,
      "material": "Clay",
      "howToUse":"Dip the utensil completely in water for a day & then fill the vessel with rice starch for few hours.When the vessel is hot do not pour cold water, let the vessel temperature come to normal then wash.",
      "WashingTips":"Always avoid Metallic scrubber rather use Soft sponge. Simply use hot water with lime. Avoid cleaning earthenware with a soap or detergent or in a dish washer.",
      "Storage":"Allow the vessel to dry completely before storage. Once in a week Fill half the vessel with water, boil for 3 min & then dispose the water to remove oil & stains, this will also strengthen & hygiene the utensil.",
      "description": "The pots are very good quality,unglazed and totally free of any toxic materials or lead and 100% Eco friendly and truly rustic. Will last many years with proper use and care (each piece comes with a product information sheet outlining the Uses and Care for the product). These Pots are hand crafted by us and its of best quality can be trusted for using years."
    },
    {
      "id": 3,
      "name": "Kadai",
      "category": "Utensils",
      "image": "/images/K2.jpg",
      "brand": "Terracotta",
      "rating": 4.5,
      "numReviews": 15,
      "Large": 1,
      "Medium": 1,
      "Small": 1,
      "countInStock":50,
      "Ldimension": "30x30x10(cm)-3.75 lts",
      "Mdimension": "26x26x9(cm)-3 lts",
      "Sdimension": "24x24x8(cm)-2 lts",
      "color": "Brown",
      "painted": 0,
      "Lprice": 450,
      "Mprice": 350,
      "Sprice": 250,
      "price":350,
      "Lstock": 50,
      "Mstock": 50,
      "Sstock": 50,
      "lid": 0,
      "material": "Clay",
      "howToUse":"Dip the utensil completely in water for a day & then fill the vessel with rice starch for few hours.When the vessel is hot do not pour cold water, let the vessel temperature come to normal then wash.",
      "WashingTips":"Always avoid Metallic scrubber rather use Soft sponge. Simply use hot water with lime. Avoid cleaning earthenware with a soap or detergent or in a dish washer.",
      "Storage":"Allow the vessel to dry completely before storage. Once in a week Fill half the vessel with water, boil for 3 min & then dispose the water to remove oil & stains, this will also strengthen & hygiene the utensil.",
      "description": "The kadai is of good quality,unglazed and totally free of any toxic materials or lead,100% Eco friendly and truly rustic. Will last many years with proper use and care (each piece comes with a product information sheet outlining the Uses and Care for the product). These Pots are hand crafted by us and its of best quality can be trusted for using years."
    },
    {
      "id": 4,
      "name": "Biryani pot",
      "category": "Utensils",
      "image": "/images/BP2.jpg",
      "brand": "Terracotta",
      "rating": 4.5,
      "numReviews": 15,
      "Large": 1,
      "Medium": 1,
      "Small": 1,
      "countInStock":50,
      "Ldimension": "30x30x19(cm)-4.5 lts",
      "Mdimension": "25x25x16.5(cm)-3.5 lts",
      "Sdimension": "22x22x15(cm)-2.5 lts",
      "color": "Brown",
      "painted": 0,
      "Lprice": 450,
      "Mprice": 350,
      "Sprice": 250,
      "price":350,
      "Lstock": 50,
      "Mstock": 50,
      "Sstock": 50,
      "lid": 1,
      "material": "Clay",
      "howToUse":"Dip the utensil completely in water for a day & then fill the vessel with rice starch for few hours.When the vessel is hot do not pour cold water, let the vessel temperature come to normal then wash.",
      "WashingTips":"Always avoid Metallic scrubber rather use Soft sponge. Simply use hot water with lime. Avoid cleaning earthenware with a soap or detergent or in a dish washer.",
      "Storage":"Allow the vessel to dry completely before storage. Once in a week Fill half the vessel with water, boil for 3 min & then dispose the water to remove oil & stains, this will also strengthen & hygiene the utensil.",
      "description": "The biryani pots are of very good quality,unglazed and totally free of any toxic materials or lead and 100% Eco friendly and truly rustic. Will last many years with proper use and care (each piece comes with a product information sheet outlining the Uses and Care for the product). These Pots are hand crafted by us and its of best quality can be trusted for using years."
   
    },
    {
      "id": 5,
      "name": "Fish curry pot",
      "category": "Utensils",
      "image": "/images/FP2.jpg",
      "brand": "Terracotta",
      "rating": 4.5,
      "numReviews": 15,
      "Large": 1,
      "Medium": 1,
      "Small": 1,
      "countInStock":50,
      "Ldimension": "30x30x13(cm)-3.75 lts",
      "Mdimension": "25x25x12(cm)-3 lts",
      "Sdimension": "22x22x12(cm)-2 lts",
      "color": "Brown",
      "painted": 0,
      "Lprice": 450,
      "Mprice": 370,
      "Sprice": 250,
      "price":350,
      "Lstock": 50,
      "Mstock": 50,
      "Sstock": 50,
      "lid": 1,
      "material": "Clay",
      "howToUse":"Dip the utensil completely in water for a day & then fill the vessel with rice starch for few hours.When the vessel is hot do not pour cold water, let the vessel temperature come to normal then wash.",
      "WashingTips":"Always avoid Metallic scrubber rather use Soft sponge. Simply use hot water with lime. Avoid cleaning earthenware with a soap or detergent or in a dish washer.",
      "Storage":"Allow the vessel to dry completely before storage. Once in a week Fill half the vessel with water, boil for 3 min & then dispose the water to remove oil & stains, this will also strengthen & hygiene the utensil.",
      "description": "The Fish curry pots are of very good quality,unglazed and totally free of any toxic materials or lead and 100% Eco friendly and truly rustic. Will last many years with proper use and care (each piece comes with a product information sheet outlining the Uses and Care for the product). These Pots are hand crafted by us and its of best quality can be trusted for using years."
    },
  ],
};
export default data;
